//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laithan_smk_restaurant.data.source.edm
{
    using System;
    using System.Collections.Generic;
    
    public partial class headerorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public headerorder()
        {
            this.detailorders = new HashSet<detailorder>();
        }
    
        public string order_id { get; set; }
        public string employee_id { get; set; }
        public string member_id { get; set; }
        public System.DateTime date { get; set; }
        public string payment { get; set; }
        public string bank { get; set; }
        public string order_status { get; set; }
        public int total_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailorder> detailorders { get; set; }
        public virtual msemployee msemployee { get; set; }
        public virtual msmember msmember { get; set; }
    }
}
