//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laithan_smk_restaurant.data.source.edm
{
    using System;
    using System.Collections.Generic;
    
    public partial class msmember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msmember()
        {
            this.headerorders = new HashSet<headerorder>();
        }
    
        public string member_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string handphone { get; set; }
        public System.DateTime join_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<headerorder> headerorders { get; set; }
    }
}
